spring:
  application:
    name: homework
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_test?currentSchema=public&options=-c%20TimeZone=Asia/Seoul
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

api:
  v1: /api/v1